// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.API.Data;

#nullable disable

namespace Web.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709102119_addisDeletedColumnFalseValue")]
    partial class addisDeletedColumnFalseValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRBranch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BMEmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRBranch");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HREmployee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HRBranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("HRCorporateTitleId")
                        .HasColumnType("bigint");

                    b.Property<long>("HRFunctionalTitleId")
                        .HasColumnType("bigint");

                    b.Property<long>("HRRoleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRBranch")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRCorporateTitle")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRFunctionalTitle")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRRole")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageGUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPasswordAlterDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoginAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PasswordExpiryPeriod")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemporaryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HRBranchId");

                    b.HasIndex("HRCorporateTitleId");

                    b.HasIndex("HRFunctionalTitleId");

                    b.HasIndex("HRRoleId");

                    b.ToTable("HREmployee");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HREmployeePermissionLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CreateOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("EditOnly")
                        .HasColumnType("bit");

                    b.Property<long>("HREmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("HRPermissionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HRRolePermissionLinkId")
                        .HasColumnType("bigint");

                    b.Property<long>("IDHREmployee")
                        .HasColumnType("bigint");

                    b.Property<long>("IDHRPermission")
                        .HasColumnType("bigint");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HREmployeeId");

                    b.HasIndex("HRPermissionId");

                    b.HasIndex("HRRolePermissionLinkId");

                    b.ToTable("HREmployeePermissionLink");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ChildOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdParentPermission")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ParentOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRPermission");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRRole");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRRolePermissionLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CreateOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("EditOnly")
                        .HasColumnType("bit");

                    b.Property<long>("HRPermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("HRRoleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRPermission")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRRole")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HRPermissionId");

                    b.HasIndex("HRRoleId");

                    b.ToTable("HRRolePermissionLink");
                });

            modelBuilder.Entity("Web.API.Entities.HRCorporateTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LevelGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxBasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxVehicleAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinBasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRCorporateTitle");
                });

            modelBuilder.Entity("Web.API.Entities.HRFunctionalTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionOrder")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRFunctionalTitle");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HREmployee", b =>
                {
                    b.HasOne("MyTestMvc.Models.Setup.HRBranch", "HRBranch")
                        .WithMany("HREmployees")
                        .HasForeignKey("HRBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.API.Entities.HRCorporateTitle", "HRCorporateTitle")
                        .WithMany("HREmployees")
                        .HasForeignKey("HRCorporateTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.API.Entities.HRFunctionalTitle", "HRFunctionalTitle")
                        .WithMany("HREmployees")
                        .HasForeignKey("HRFunctionalTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTestMvc.Models.Setup.HRRole", "HRRole")
                        .WithMany("HREmployees")
                        .HasForeignKey("HRRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HRBranch");

                    b.Navigation("HRCorporateTitle");

                    b.Navigation("HRFunctionalTitle");

                    b.Navigation("HRRole");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HREmployeePermissionLink", b =>
                {
                    b.HasOne("MyTestMvc.Models.Setup.HREmployee", "HREmployee")
                        .WithMany("HREmployeePermissionLink")
                        .HasForeignKey("HREmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTestMvc.Models.Setup.HRPermission", "HRPermission")
                        .WithMany()
                        .HasForeignKey("HRPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTestMvc.Models.Setup.HRRolePermissionLink", null)
                        .WithMany("HREmployeePermissionLinks")
                        .HasForeignKey("HRRolePermissionLinkId");

                    b.Navigation("HREmployee");

                    b.Navigation("HRPermission");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRRolePermissionLink", b =>
                {
                    b.HasOne("MyTestMvc.Models.Setup.HRPermission", "HRPermission")
                        .WithMany("HRRolePermissionLinks")
                        .HasForeignKey("HRPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTestMvc.Models.Setup.HRRole", "HRRole")
                        .WithMany("HRRolePermissionLinks")
                        .HasForeignKey("HRRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HRPermission");

                    b.Navigation("HRRole");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRBranch", b =>
                {
                    b.Navigation("HREmployees");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HREmployee", b =>
                {
                    b.Navigation("HREmployeePermissionLink");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRPermission", b =>
                {
                    b.Navigation("HRRolePermissionLinks");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRRole", b =>
                {
                    b.Navigation("HREmployees");

                    b.Navigation("HRRolePermissionLinks");
                });

            modelBuilder.Entity("MyTestMvc.Models.Setup.HRRolePermissionLink", b =>
                {
                    b.Navigation("HREmployeePermissionLinks");
                });

            modelBuilder.Entity("Web.API.Entities.HRCorporateTitle", b =>
                {
                    b.Navigation("HREmployees");
                });

            modelBuilder.Entity("Web.API.Entities.HRFunctionalTitle", b =>
                {
                    b.Navigation("HREmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
