// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.API.Data;

#nullable disable

namespace Web.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.API.Models.DTOS.HRPermissionEmployeeRoleDto", b =>
                {
                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ChildOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CreateOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Created_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EditOnly")
                        .HasColumnType("bit");

                    b.Property<string>("FontIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdHREmployee")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdHRPermission")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdHRRole")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdParentPermission")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("datetime2");

                    b.ToTable("HRPermissionEmployeeRoleDto");
                });

            modelBuilder.Entity("Web.API.Models.Entities.HRCorporateTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LevelGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxBasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxVehicleAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinBasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRCorporateTitle");
                });

            modelBuilder.Entity("Web.API.Models.Entities.HRFunctionalTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PositionOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRFunctionalTitle");
                });

            modelBuilder.Entity("Web.API.Models.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<long>("IDHREmployee")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IDHREmployee");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRBranch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BMEmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRBranch");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoginAttempt")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRCompany");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HREmployee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRBranch")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRCorporateTitle")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRFunctionalTitle")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRRole")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageGUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPasswordAlterDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LoginAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PasswordExpiryPeriod")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemporaryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdHRBranch");

                    b.HasIndex("IdHRCorporateTitle");

                    b.HasIndex("IdHRFunctionalTitle");

                    b.HasIndex("IdHRRole");

                    b.ToTable("HREmployee");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HREmployeePermissionLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CreateOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("EditOnly")
                        .HasColumnType("bit");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHREmployee")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRPermission")
                        .HasColumnType("bigint");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdHREmployee");

                    b.HasIndex("IdHRPermission");

                    b.ToTable("HREmployeePermissionLink");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HREmployeePermissionLinkMirror", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CreateOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("EditOnly")
                        .HasColumnType("bit");

                    b.Property<long>("IDHREmployee")
                        .HasColumnType("bigint");

                    b.Property<long>("IDHRPermission")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HREmployeePermissionLinkMirror");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ChildOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<long>("IdParentPermission")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ParentOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRPermission");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_On")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HRRole");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRRolePermissionLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CreateOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("EditOnly")
                        .HasColumnType("bit");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRPermission")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRRole")
                        .HasColumnType("bigint");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdHRPermission");

                    b.HasIndex("IdHRRole");

                    b.ToTable("HRRolePermissionLink");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRRolePermissionLinkMirror", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CreateOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("EditOnly")
                        .HasColumnType("bit");

                    b.Property<long>("IdHRCompany")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRPermission")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHRRole")
                        .HasColumnType("bigint");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HRRolePermissionLinkMirror");
                });

            modelBuilder.Entity("Web.API.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("Web.API.Models.Setup.HREmployee", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IDHREmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HREmployee", b =>
                {
                    b.HasOne("Web.API.Models.Setup.HRBranch", "HRBranch")
                        .WithMany("HREmployees")
                        .HasForeignKey("IdHRBranch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.API.Models.Entities.HRCorporateTitle", "HRCorporateTitle")
                        .WithMany("HREmployees")
                        .HasForeignKey("IdHRCorporateTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.API.Models.Entities.HRFunctionalTitle", "HRFunctionalTitle")
                        .WithMany("HREmployees")
                        .HasForeignKey("IdHRFunctionalTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.API.Models.Setup.HRRole", "HRRole")
                        .WithMany("HREmployees")
                        .HasForeignKey("IdHRRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HRBranch");

                    b.Navigation("HRCorporateTitle");

                    b.Navigation("HRFunctionalTitle");

                    b.Navigation("HRRole");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HREmployeePermissionLink", b =>
                {
                    b.HasOne("Web.API.Models.Setup.HREmployee", "HREmployee")
                        .WithMany()
                        .HasForeignKey("IdHREmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.API.Models.Setup.HRPermission", "HRPermission")
                        .WithMany()
                        .HasForeignKey("IdHRPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HREmployee");

                    b.Navigation("HRPermission");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRRolePermissionLink", b =>
                {
                    b.HasOne("Web.API.Models.Setup.HRPermission", "HRPermission")
                        .WithMany("HRRolePermissionLinks")
                        .HasForeignKey("IdHRPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.API.Models.Setup.HRRole", "HRRole")
                        .WithMany("HRRolePermissionLinks")
                        .HasForeignKey("IdHRRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HRPermission");

                    b.Navigation("HRRole");
                });

            modelBuilder.Entity("Web.API.Models.Entities.HRCorporateTitle", b =>
                {
                    b.Navigation("HREmployees");
                });

            modelBuilder.Entity("Web.API.Models.Entities.HRFunctionalTitle", b =>
                {
                    b.Navigation("HREmployees");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRBranch", b =>
                {
                    b.Navigation("HREmployees");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HREmployee", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRPermission", b =>
                {
                    b.Navigation("HRRolePermissionLinks");
                });

            modelBuilder.Entity("Web.API.Models.Setup.HRRole", b =>
                {
                    b.Navigation("HREmployees");

                    b.Navigation("HRRolePermissionLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
