INSERT INTO HRPermission
(
    IdParentPermission,
    Title,
    Description,
    Area,
    Controller,
    Action,
    PermissionCode,
    ParentOrder,
    ChildOrder,
    FontIcon,
    AreaIcon,
    IsActive,
    Created_By,
    Updated_By,
    Created_On,
    Updated_On,
    IdGUID,
    IsDeleted,
    IdHRCompany
)
SELECT
    0 AS IdParentPermission,
    'Employee' AS Title,
    'Employee Management' AS Description,
    'Setup' AS Area,
    'HREmployee' AS Controller,
    'GetEmployees' AS Action,
    'SETUP_EMPLOYEE_VIEW' AS PermissionCode,
    1 AS ParentOrder,
    1 AS ChildOrder,
    'bi bi-people' AS FontIcon,
    'bi bi-gear' AS AreaIcon,
    1 AS IsActive,
    'System' AS Created_By,
    'System' AS Updated_By,
    GETDATE() AS Created_On,
    Getdate() AS Updated_On,
    NEWID() AS IdGUID,
    0 AS IsDeleted,
    1 AS IdHRCompany;